#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

name: $(SourceBranchName).$(Date:yyyyMMdd)$(Rev:.r)

# Configure which branches trigger builds
trigger:
  batch: true
  branches:
    include:
    - master
    - 202*
    - ci
pr: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: HandsonTableBuild
  jobs:
  - job: HandsonTableBuild
    steps:
    - pwsh: |
        $ErrorView = 'NormalView'
        npm ci
        npm run build
      displayName: Build
    # - pwsh: |
    #     npm test
    #   displayName: Test
    - task: Npm@1
      inputs:
        command: 'publish'
        workingDir: '.'
        publishRegistry: 'useFeed'
        publishFeed: 'e84149e9-8de5-4b69-a182-b1b2a38fcd9b/7c1794ab-ecdb-40bf-bdad-03d4813bf3f8'
      displayName: Publish
